In [1]:
# Import Required Libraries
import pandas as pd
import numpy as np


# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load the dataset
df = pd.read_csv("../dataset/raw/airline_delay.csv",encoding="latin1")

# Display the first five rows
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1998,1,1,2,5,1998-01-02,NW,19386,NW,N297US,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,2,5,28,4,2009-05-28,FL,20437,FL,N946AT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013,2,6,29,6,2013-06-29,MQ,20398,MQ,N665MQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,3,8,31,2,2010-08-31,DL,19790,DL,N6705Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006,1,1,15,7,2006-01-15,US,20355,US,N504AU,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Dataset Shape
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Rows    : 2,000,000
Columns : 109

In [4]:
#Data Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000000 entries, 0 to 1999999
Columns: 109 entries, Year to Div5TailNum
dtypes: float64(72), int64(18), object(19)
memory usage: 1.6+ GB

In [5]:
#Column Names
df.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum']

In [6]:
# Data types of all columns
df.dtypes

Year                  int64
Quarter               int64
Month                 int64
DayofMonth            int64
DayOfWeek             int64
                     ...
Div5WheelsOn        float64
Div5TotalGTime      float64
Div5LongestGTime    float64
Div5WheelsOff       float64
Div5TailNum         float64
Length: 109, dtype: object

In [7]:
numerical_cols = df.select_dtypes(include=["number"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

print(f"Numerical Columns   : {len(numerical_cols)}")
print(f"Categorical Columns : {len(categorical_cols)}")

Numerical Columns   : 90
Categorical Columns : 19

In [8]:
#Missing Values
missing = pd.DataFrame({"Missing Values": df.isnull().sum(),"Percentage (%)": round(df.isnull().mean() * 100, 2)})

missing = missing.sort_values(by="Missing Values",ascending=False)

missing

                  Missing Values  Percentage (%)
Div5TailNum              2000000           100.0
Div4TotalGTime           2000000           100.0
Div3AirportSeqID         2000000           100.0
Div3WheelsOn             2000000           100.0
Div3Airport              2000000           100.0
...                          ...             ...
ArrTimeBlk                     0             0.0
Cancelled                      0             0.0
Diverted                       0             0.0
Flights                        0             0.0
Distance                       0             0.0

[109 rows x 2 columns]

In [9]:
#Duplicate Rows
duplicates = df.duplicated().sum()

print(f"Duplicate Records : {duplicates}")

Duplicate Records : 0

In [10]:
#Description of Numerical Columns
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Year,2000000.0,2004.313701,9.228930,1987.0,1997.0,2005.0,2012.0,2020.0
Quarter,2000000.0,2.501267,1.118022,1.0,1.0,3.0,3.0,4.0
Month,2000000.0,6.500761,3.443460,1.0,3.0,7.0,9.0,12.0
DayofMonth,2000000.0,15.722019,8.778412,1.0,8.0,16.0,23.0,31.0
DayOfWeek,2000000.0,3.937445,1.990369,1.0,2.0,4.0,6.0,7.0
...,...,...,...,...,...,...,...,...
Div5WheelsOn,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Div5TotalGTime,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Div5LongestGTime,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Div5WheelsOff,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Div5TailNum,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Description of Categorical Columns
df[categorical_cols].describe().T

                               count unique          top    freq
FlightDate                   2000000  11871   2019-07-22     264
Reporting_Airline            2000000     33           WN  306238
IATA_CODE_Reporting_Airline  2000000     35           WN  306238
Tail_Number                  1608237  17210       UNKNOW    5765
Origin                       2000000    406          ATL  108667
OriginCityName               2000000    400  Chicago, IL  125262
OriginState                  1999354     53           CA  235509
OriginStateName              1999354     53   California  235509
Dest                         2000000    408          ATL  108112
DestCityName                 2000000    403  Chicago, IL  125466
DestState                    1999406     53           CA  235341
DestStateName                1999406     53   California  235341
DepTimeBlk                   2000000     19    0800-0859  140385
ArrTimeBlk                   2000000     19    1600-1659  136852
CancellationCode               20220      4            B    8469
Div1Airport                     1881    225          DEN      65
Div1TailNum                     1514   1307       N14570       3
Div2Airport                       14     11          IAH       3
Div2TailNum                        3      3       N793SK       1

In [12]:
selected_columns = [

    # Date Information
    "Year",
    "Quarter",
    "Month",
    "DayofMonth",
    "DayOfWeek",
    "FlightDate",

    # Airline
    "Reporting_Airline",

    # Origin Airport
    "Origin",
    "OriginCityName",
    "OriginState",

    # Destination Airport
    "Dest",
    "DestCityName",
    "DestState",

    # Flight Delays
    "DepDelay",
    "DepDelayMinutes",
    "ArrDelay",
    "ArrDelayMinutes",

    # Delay Causes
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay",

    # Flight Status
    "Cancelled",
    "CancellationCode",
    "Diverted",

    # Flight Distance
    "Distance",
    "DistanceGroup"
]

df = df[selected_columns]

In [13]:
# Save the filtered dataset
df.to_csv("../dataset/processed/airline_delay_selected.csv", index=False)

print("Filtered dataset saved successfully!")

Filtered dataset saved successfully!

# Key Observations

- The dataset contains **2M flight records** and **109 features**, making it suitable for large-scale exploratory data analysis.
- The dataset includes information related to flight schedules, airlines, airports, delays, cancellations, and delay causes.
- Missing values are primarily present in delay-related and diversion-related columns, which will require careful handling during data preprocessing.
- The dataset contains **0 duplicate records**, which will be evaluated during the cleaning phase.
- Since the dataset consists of **109 features**, only columns relevant to airline delay analysis will be selected to improve efficiency and maintain analytical focus.

## Next Steps

- Handle missing values and duplicate records.
- Select relevant features for analysis.
- Convert date and time columns into appropriate formats.
- Prepare the dataset for exploratory data analysis.